import type { Metadata } from "next";
import NavbarLayout from "@FE/components/navbar/NavbarLayout";
import SideBar from "@FE/components/sideBar/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="drawer">
      <input id="my-drawer-3" type="checkbox" className="drawer-toggle" />
      <div className="drawer-content flex flex-col">
        {/* Navbar */}
        <NavbarLayout />
        {/* Page content here */}
        {children}
      </div>
      {/* SideBar */}
      <SideBar />
    </div>
  );
}
