import type { Metadata } from "next";
import NavbarLayout from "@FE/components/navbar/NavbarLayout";
import SideBar from "@FE/components/sideBar/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="flex flex-col py-0">
        {/* Navbar */}
        <NavbarLayout />
        {/* SideBar */}
        <SideBar />
      </div>
      {/* Page content here */}
      {children}
    </>
  );
}
